#!/usr/bin/env python3
"""Build the inline SVG icon sprite from Phosphor Icons.

The app has no bundler and has to work offline, so icons are not a webfont and
not a CDN request: they are <symbol> definitions spliced straight into
index.html between the ICONS:START / ICONS:END markers. Markup then references
them with <svg class="icon"><use href="#i-name"/></svg>, which is a same
-document reference and therefore works in every browser (external <use> is
still unreliable in Safari).

Usage:
    python3 scripts/build_icons.py

Downloads the Phosphor tarball into scripts/cache/ on first run, the same way
the other build scripts cache their sources.
"""
import io
import pathlib
import re
import sys
import tarfile
import urllib.request

VERSION = "2.1.1"
TARBALL = f"https://registry.npmjs.org/@phosphor-icons/core/-/core-{VERSION}.tgz"

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = ROOT / "scripts" / "cache" / f"phosphor-core-{VERSION}.tgz"
INDEX = ROOT / "index.html"
FAVICON = ROOT / "assets" / "social" / "favicon.svg"

# favicon: the same globe on the app's sand tile, so the tab matches the splash
FAVICON_BG = "#d6ce93"
FAVICON_FG = "#2b2118"

START = "<!-- ICONS:START -->"
END = "<!-- ICONS:END -->"

# id in the sprite -> Phosphor asset (weight, name).
# Bold is the default: it matches the app's heavy Archivo Black / hard-shadow
# look. Fill is used where the icon reads as a badge rather than a control.
ICONS = {
    "globe": ("bold", "globe-hemisphere-west"),
    "globe-fill": ("fill", "globe-hemisphere-west"),
    "arcade": ("bold", "game-controller"),
    "daily": ("bold", "calendar-blank"),
    "worldcup": ("bold", "soccer-ball"),
    "trophy": ("fill", "trophy"),
    "fire": ("fill", "fire"),
    "sound": ("bold", "speaker-high"),
    "muted": ("bold", "speaker-slash"),
    "dark": ("bold", "moon"),
    "light": ("bold", "sun"),
    "stats": ("bold", "chart-bar"),
    "language": ("bold", "translate"),
    "close": ("bold", "x"),
    "tap": ("bold", "hand-tap"),
    "check": ("bold", "check"),
    "share": ("bold", "clipboard-text"),
    "hint": ("fill", "lightbulb"),
    "skip": ("bold", "skip-forward"),
    "timer": ("bold", "timer"),
    "record": ("fill", "confetti"),
    "cat-flag": ("bold", "flag"),
    "cat-shape": ("bold", "map-trifold"),
    "cat-capital": ("bold", "bank"),
    "cat-locate": ("bold", "map-pin"),
}


def fetch() -> tarfile.TarFile:
    if not CACHE.exists():
        print(f"downloading {TARBALL}")
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(TARBALL) as r:
            CACHE.write_bytes(r.read())
    return tarfile.open(CACHE)


def body_of(svg: str) -> str:
    """Everything inside the root <svg>, minus Phosphor's transparent spacer rect."""
    inner = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", svg, flags=re.S)
    inner = re.sub(r"<rect[^>]*fill=\"none\"[^>]*/>", "", inner)
    return inner.strip()


def main() -> int:
    tar = fetch()

    def read(weight: str, name: str) -> str:
        member = f"package/assets/{weight}/{name}-{weight}.svg"
        try:
            f = tar.extractfile(member)
        except KeyError:
            f = None
        if f is None:
            raise SystemExit(f"missing in tarball: {member}")
        return body_of(io.TextIOWrapper(f, encoding="utf-8").read())

    symbols = [
        f'<symbol id="i-{sprite_id}" viewBox="0 0 256 256">{read(weight, name)}</symbol>'
        for sprite_id, (weight, name) in ICONS.items()
    ]

    block = (
        f"{START}\n"
        f"    <!-- Phosphor Icons {VERSION} (MIT). Generated by scripts/build_icons.py — do not edit by hand. -->\n"
        '    <svg class="icon-sprite" aria-hidden="true" focusable="false">\n'
        + "".join(f"      {s}\n" for s in symbols)
        + "    </svg>\n"
        f"    {END}"
    )

    html = INDEX.read_text(encoding="utf-8")
    if START not in html or END not in html:
        print("index.html is missing the ICONS:START / ICONS:END markers", file=sys.stderr)
        return 1
    html = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, html, flags=re.S)
    INDEX.write_text(html, encoding="utf-8")
    print(f"wrote {len(symbols)} symbols into {INDEX.relative_to(ROOT)}")

    # The globe is scaled to 70% and centred, so the glyph keeps a margin inside
    # the rounded tile instead of touching its corners.
    globe = read(*ICONS["globe-fill"]).replace('fill="currentColor"', "")
    FAVICON.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">'
        f'<rect width="256" height="256" rx="56" fill="{FAVICON_BG}"/>'
        f'<g transform="translate(38.4 38.4) scale(0.7)" fill="{FAVICON_FG}">{globe}</g>'
        "</svg>\n",
        encoding="utf-8",
    )
    print(f"wrote {FAVICON.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
