// Icon helper. The <symbol> definitions live inline in index.html (see the
// ICONS:START block, generated by scripts/build_icons.py); this module only
// builds the <use> reference that points at them.
//
// Everything here returns a string rather than a node because the call sites
// are template literals building innerHTML. That is safe as long as `name` is
// a literal from the sprite — never pass user input through it.
export const icon = (name, cls = "") =>
  `<svg class="icon${cls ? " " + cls : ""}" aria-hidden="true"><use href="#i-${name}" /></svg>`;

// Same icon, as a real node, for the places that build DOM instead of markup.
export function iconEl(name, cls = "") {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("class", "icon" + (cls ? " " + cls : ""));
  svg.setAttribute("aria-hidden", "true");
  const use = document.createElementNS("http://www.w3.org/2000/svg", "use");
  use.setAttribute("href", "#i-" + name);
  svg.appendChild(use);
  return svg;
}
